version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4000:80" # 4000 for node-app, 80 for nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  mysql: # 自訂的service
    image: mysql:8
    container_name: mysql
    volumes:
      - mysql-docker-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "latin_card"
    ports:
      - "3307:3306"  
  node-app:
    depends_on:
      - mysql
    build: .
    image: jadokao/sideproject
    volumes:
      - ./:/app
    environment:
      - JWT_SECRET=FAKE
      - NODE_OPTIONS=--max-old-space-size=8192
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis-server
  redis:
    image: "redis:alpine"
volumes:
  mysql-docker-data: