version: "3.8"

services:
  mysql: # 自訂的service
    image: mysql:8
    container_name: mysql
    volumes:
      - mysql-docker-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "latin_card"
      REDIS_URL: "redis://redis:6379"
      REDIS_HOST: "redis-server"
    ports:
      - "3307:3306"  
  node-app:
    depends_on:
      - mysql
    build: .
    image: jadokao/sideproject
    ports:
      - "4001:4000"
    volumes:
      - ./:/app
    environment:
      - JWT_SECRET=FAKE
      - NODE_OPTIONS=--max-old-space-size=8192
  redis:
    image: "redis:alpine"
volumes:
  mysql-docker-data: